version: "3"

services:
  postgres:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USERNAME: postgres
      POSTGRES_PASSWORD: graduatenu
      POSTGRES_DB: dev
    volumes:
      - ./graduatenu-db-data:/var/lib/postgresql/data

volumes:
  graudatenu_db_data:
