name: CI

on: [push]

jobs:
  run-scrapers-tests:
    runs-on: ubuntu-latest
    name: Scraper Tests
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "14"
      - name: Run Jest Tests
        run: |
          cd scrapers 
          yarn install
          yarn test
  run-api-v2-tests:
    runs-on: ubuntu-latest
    name: API V2 Tests
    steps:
      - uses: actions/checkout@v1
      - name: Setup node
        uses: actions/setup-node@v1
        with:
          node-version: "16"
      - name: Run Jest Tests
        run: |
          cd api-v2
          yarn install
          yarn test
  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image for frontend
        run: |
          docker build -t frontend -f frontend/Dockerfile .
  build-api-image-and-run-tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build Docker image and run tests for api
        run: |
          cd api
          docker-compose run server rails test
