name: CI

on: [push]

jobs:
  lint:
    runs-on: ubuntu-latest
    name: Run linting for all packages
    steps:
      - uses: actions/checkout@v3
      - name: install node v16
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - uses: bahmutov/npm-install@v1
      - run: yarn lint
  run-api-v2-tests:
    runs-on: ubuntu-latest
    name: API V2 Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn install --immutable
      - name: Run Jest Tests
        run: yarn packages/api-v2 test
  run-api-e2e-tests:
    runs-on: ubuntu-latest
    name: Backend E2E Tests
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup node
        uses: actions/setup-node@v3
        with:
          node-version: "16"
      - run: yarn install --immutable
      - name: Start up test db
        run: yarn test:db:up
      - name: Run E2E tests
        run: yarn test:e2e
      - name: Tear down test db
        run: yarn test:db:down
  build-frontend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: yarn install --immutable
      - name: Build Docker image for frontend
        run: yarn frontend:docker:build
  build-backend-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - run: yarn install --immutable
      - name: Build Docker image for backend
        run: yarn backend:docker:build
